/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

new Handle:h_timer = INVALID_HANDLE;

public Plugin:myinfo = 
{
	name = "PlayTimeTouchGrass",
	author = "Fadil (clownCoder",
	description = "<- Description ->",
	version = "1.0 and only version ever xd",
	url = ""
}

public OnClientPutInServer(client)
{
	CreateTimer(10800.0, TimerCallBack);
	
}

public Action:TimerCallBack(Handle:Timer,  any:client)
{
	PrintToChat (client, "[SM} You've Been Here for 3 Hours! Go Touch some grass xd");
	CloseHandle (h_timer);
}